/*******************************************************************************
 * Copyright (c) 2005 BEA Systems, Inc. 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    mkaufman@bea.com - initial API and implementation
 *    
 *******************************************************************************/

package org.eclipse.jdt.core.compiler;

/**
 * An result class used as a return value from ICompilationParticipant's notify() method 
 * when responding to a pre-reconcile event.
 * 
 * @see ICompilationParticipant#notify(CompilationParticipantEvent)
 * @since 3.2
 */
public class PreReconcileCompilationResult extends CompilationParticipantResult {

	public PreReconcileCompilationResult(final IProblem[] problems )
	{
		_problems = problems;
	}
	
	/**
	 * @return an integer flag indicating that this is result for a pre-reconcile event.
	 * @see ICompilationParticipant#PRE_RECONCILE_EVENT
	 * @see CompilationParticipantEvent#getKind()
	 */
	public final int getKind() { return ICompilationParticipant.PRE_RECONCILE_EVENT; }
	
	/**
	 * @return the array of problems generated by the participant during reconcile 
	 */
	public IProblem[] getProblems(){ return _problems; }

	private final IProblem[] _problems;

}
