/*******************************************************************************
 * Copyright (c) 2020 Thomas Wolf <thomas.wolf@paranor.ch> and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
/*
 * Target for annotation processing test.  Processing this
 * should result in generation of a class gen.WarnGen with
 * method public String foo().
 * @see org.eclipse.jdt.compiler.apt.tests.processors.genclass.GenClassProc.
 */
package targets.dispatch;

import org.eclipse.jdt.compiler.apt.tests.annotations.GenClass;

// This class will be generated by the annotation processor
import gen.WarnGen;

@GenClass(clazz="gen.WarnGen", method="foo", warn=true)
public class WarnGenClass {
	String get() {
		return (new WarnGen()).foo();
	}
}
