package test0541;

class A {
    private int[] tab = new int[] {
        B.CODNIVEL3, B.NOMNIVEL3, B.CODAUTORIZA,
        B.NOMUSRCIA, B.TIPAUTORIZA, B.NOMAUTORIZA,
        B.CODCTOAUTORIZA, B.NOMCTOAUTORIZA, B.CODMON,
        B.NOMMON, B.MCAINH, B.IMPORTEAUTORIZA,
        B.NUMDECIMALES
    };   
}