/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003,
							TokenNameSingleQuoteStringLiteral = 1004;

	static boolean isRestrictedKeyword(int tokenType) {
		return switch (tokenType) {
			case TokenNameRestrictedIdentifierYield, TokenNameRestrictedIdentifierrecord,TokenNameRestrictedIdentifierWhen,
					TokenNameRestrictedIdentifiersealed, TokenNameRestrictedIdentifierpermits -> true;
			default -> false;
		};
	}

	static int getRestrictedKeyword(char [] text) {
		if (text != null) {
			int len = text.length;
			if (len == 4 && text[0] == 'w' ||
				len == 5 && text[0] == 'y' ||
				len == 6 && (text[0] == 'r' || text[0] == 's') ||
				len == 7 && text[0] == 'p') {
				return getRestrictedKeyword(new String(text));
			}
		}
		return TokenNameNotAToken;
	}

	static int getRestrictedKeyword(String text) {
		return switch (text) {
			case "yield"   -> TokenNameRestrictedIdentifierYield;   //$NON-NLS-1$
			case "record"  -> TokenNameRestrictedIdentifierrecord;  //$NON-NLS-1$
			case "when"    -> TokenNameRestrictedIdentifierWhen;    //$NON-NLS-1$
			case "sealed"  -> TokenNameRestrictedIdentifiersealed;  //$NON-NLS-1$
			case "permits" -> TokenNameRestrictedIdentifierpermits; //$NON-NLS-1$
			default        -> TokenNameNotAToken;
		};
	}

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 22,
							TokenNameabstract = 44,
							TokenNameassert = 81,
							TokenNameboolean = 105,
							TokenNamebreak = 82,
							TokenNamebyte = 106,
							TokenNamecase = 91,
							TokenNamecatch = 107,
							TokenNamechar = 108,
							TokenNameclass = 70,
							TokenNamecontinue = 83,
							TokenNameconst = 138,
							TokenNamedefault = 76,
							TokenNamedo = 84,
							TokenNamedouble = 109,
							TokenNameelse = 123,
							TokenNameenum = 74,
							TokenNameextends = 92,
							TokenNamefalse = 54,
							TokenNamefinal = 45,
							TokenNamefinally = 116,
							TokenNamefloat = 110,
							TokenNamefor = 85,
							TokenNamegoto = 139,
							TokenNameif = 86,
							TokenNameimplements = 135,
							TokenNameimport = 111,
							TokenNameinstanceof = 16,
							TokenNameint = 112,
							TokenNameinterface = 73,
							TokenNamelong = 113,
							TokenNamenative = 46,
							TokenNamenew = 38,
							TokenNamenon_sealed = 47,
							TokenNamenull = 55,
							TokenNamepackage = 90,
							TokenNameprivate = 48,
							TokenNameprotected = 49,
							TokenNamepublic = 50,
							TokenNamereturn = 87,
							TokenNameshort = 114,
							TokenNamestatic = 37,
							TokenNamestrictfp = 51,
							TokenNamesuper = 34,
							TokenNameswitch = 64,
							TokenNamesynchronized = 39,
							TokenNamethis = 35,
							TokenNamethrow = 78,
							TokenNamethrows = 117,
							TokenNametransient = 52,
							TokenNametrue = 56,
							TokenNametry = 88,
							TokenNamevoid = 115,
							TokenNamevolatile = 53,
							TokenNamewhile = 79,
							TokenNamemodule = 118,
							TokenNameopen = 119,
							TokenNamerequires = 124,
							TokenNametransitive = 130,
							TokenNameexports = 125,
							TokenNameopens = 126,
							TokenNameto = 136,
							TokenNameuses = 127,
							TokenNameprovides = 128,
							TokenNamewith = 137,
							TokenNameIntegerLiteral = 57,
							TokenNameLongLiteral = 58,
							TokenNameFloatingPointLiteral = 59,
							TokenNameDoubleLiteral = 60,
							TokenNameCharacterLiteral = 61,
							TokenNameStringLiteral = 41,
							TokenNameTextBlock = 42,
							TokenNameStringTemplate = 120,
							TokenNameTextBlockTemplate = 121,
							TokenNamePLUS_PLUS = 2,
							TokenNameMINUS_MINUS = 3,
							TokenNameEQUAL_EQUAL = 19,
							TokenNameLESS_EQUAL = 12,
							TokenNameGREATER_EQUAL = 13,
							TokenNameNOT_EQUAL = 20,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 14,
							TokenNameUNSIGNED_RIGHT_SHIFT = 17,
							TokenNamePLUS_EQUAL = 93,
							TokenNameMINUS_EQUAL = 94,
							TokenNameMULTIPLY_EQUAL = 95,
							TokenNameDIVIDE_EQUAL = 96,
							TokenNameAND_EQUAL = 97,
							TokenNameOR_EQUAL = 98,
							TokenNameXOR_EQUAL = 99,
							TokenNameREMAINDER_EQUAL = 100,
							TokenNameLEFT_SHIFT_EQUAL = 101,
							TokenNameRIGHT_SHIFT_EQUAL = 102,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 103,
							TokenNameOR_OR = 31,
							TokenNameAND_AND = 30,
							TokenNamePLUS = 4,
							TokenNameMINUS = 5,
							TokenNameNOT = 66,
							TokenNameREMAINDER = 9,
							TokenNameXOR = 24,
							TokenNameAND = 21,
							TokenNameMULTIPLY = 8,
							TokenNameOR = 27,
							TokenNameTWIDDLE = 67,
							TokenNameDIVIDE = 10,
							TokenNameGREATER = 15,
							TokenNameLESS = 11,
							TokenNameLPAREN = 23,
							TokenNameRPAREN = 25,
							TokenNameLBRACE = 40,
							TokenNameRBRACE = 33,
							TokenNameLBRACKET = 6,
							TokenNameRBRACKET = 68,
							TokenNameSEMICOLON = 26,
							TokenNameQUESTION = 29,
							TokenNameCOLON = 65,
							TokenNameCOMMA = 32,
							TokenNameDOT = 1,
							TokenNameEQUAL = 77,
							TokenNameAT = 36,
							TokenNameELLIPSIS = 122,
							TokenNameARROW = 104,
							TokenNameCOLON_COLON = 7,
							TokenNameBeginLambda = 62,
							TokenNameBeginIntersectionCast = 69,
							TokenNameBeginTypeArguments = 89,
							TokenNameElidedSemicolonAndRightBrace = 71,
							TokenNameAT308 = 28,
							TokenNameAT308DOTDOTDOT = 131,
							TokenNameBeginCaseExpr = 72,
							TokenNameRestrictedIdentifierYield = 80,
							TokenNameRestrictedIdentifierrecord = 75,
							TokenNameRestrictedIdentifiersealed = 43,
							TokenNameRestrictedIdentifierpermits = 129,
							TokenNameBeginCaseElement = 132,
							TokenNameRestrictedIdentifierWhen = 133,
							TokenNameBeginRecordPattern = 134,
							TokenNameEOF = 63,
							TokenNameERROR = 140;
}
