/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
							TokenNameWHITESPACE = 1000,
							TokenNameCOMMENT_LINE = 1001,
							TokenNameCOMMENT_BLOCK = 1002,
							TokenNameCOMMENT_JAVADOC = 1003,
							TokenNameSingleQuoteStringLiteral = 1004;

	static boolean isRestrictedKeyword(int tokenType) {
		return switch (tokenType) {
			case TokenNameRestrictedIdentifierYield, TokenNameRestrictedIdentifierrecord,TokenNameRestrictedIdentifierWhen,
					TokenNameRestrictedIdentifiersealed, TokenNameRestrictedIdentifierpermits -> true;
			default -> false;
		};
	}

	static int getRestrictedKeyword(char [] text) {
		if (text != null) {
			int len = text.length;
			if (len == 4 && text[0] == 'w' ||
				len == 5 && text[0] == 'y' ||
				len == 6 && (text[0] == 'r' || text[0] == 's') ||
				len == 7 && text[0] == 'p') {
				return getRestrictedKeyword(new String(text));
			}
		}
		return TokenNameNotAToken;
	}

	static int getRestrictedKeyword(String text) {
		return switch (text) {
			case "yield"   -> TokenNameRestrictedIdentifierYield;   //$NON-NLS-1$
			case "record"  -> TokenNameRestrictedIdentifierrecord;  //$NON-NLS-1$
			case "when"    -> TokenNameRestrictedIdentifierWhen;    //$NON-NLS-1$
			case "sealed"  -> TokenNameRestrictedIdentifiersealed;  //$NON-NLS-1$
			case "permits" -> TokenNameRestrictedIdentifierpermits; //$NON-NLS-1$
			default        -> TokenNameNotAToken;
		};
	}

	// BEGIN_AUTOGENERATED_REGION
	int TokenNameIdentifier = 27,
							TokenNameabstract = 44,
							TokenNameassert = 91,
							TokenNameboolean = 103,
							TokenNamebreak = 92,
							TokenNamebyte = 104,
							TokenNamecase = 101,
							TokenNamecatch = 105,
							TokenNamechar = 106,
							TokenNameclass = 80,
							TokenNamecontinue = 93,
							TokenNameconst = 137,
							TokenNamedefault = 86,
							TokenNamedo = 94,
							TokenNamedouble = 107,
							TokenNameelse = 122,
							TokenNameenum = 83,
							TokenNameextends = 102,
							TokenNamefalse = 45,
							TokenNamefinal = 46,
							TokenNamefinally = 115,
							TokenNamefloat = 108,
							TokenNamefor = 95,
							TokenNamegoto = 138,
							TokenNameif = 96,
							TokenNameimplements = 134,
							TokenNameimport = 109,
							TokenNameinstanceof = 16,
							TokenNameint = 110,
							TokenNameinterface = 82,
							TokenNamelong = 111,
							TokenNamenative = 47,
							TokenNamenew = 36,
							TokenNamenon_sealed = 48,
							TokenNamenull = 49,
							TokenNamepackage = 100,
							TokenNameprivate = 50,
							TokenNameprotected = 51,
							TokenNamepublic = 52,
							TokenNamereturn = 97,
							TokenNameshort = 112,
							TokenNamestatic = 38,
							TokenNamestrictfp = 53,
							TokenNamesuper = 34,
							TokenNameswitch = 62,
							TokenNamesynchronized = 42,
							TokenNamethis = 35,
							TokenNamethrow = 88,
							TokenNamethrows = 116,
							TokenNametransient = 54,
							TokenNametrue = 55,
							TokenNametry = 98,
							TokenNamevoid = 113,
							TokenNamevolatile = 56,
							TokenNamewhile = 89,
							TokenNamemodule = 117,
							TokenNameopen = 118,
							TokenNamerequires = 123,
							TokenNametransitive = 129,
							TokenNameexports = 124,
							TokenNameopens = 125,
							TokenNameto = 135,
							TokenNameuses = 126,
							TokenNameprovides = 127,
							TokenNamewith = 136,
							TokenNameIntegerLiteral = 57,
							TokenNameLongLiteral = 58,
							TokenNameFloatingPointLiteral = 59,
							TokenNameDoubleLiteral = 60,
							TokenNameCharacterLiteral = 61,
							TokenNameStringLiteral = 39,
							TokenNameTextBlock = 40,
							TokenNameStringTemplate = 119,
							TokenNameTextBlockTemplate = 120,
							TokenNamePLUS_PLUS = 10,
							TokenNameMINUS_MINUS = 11,
							TokenNameEQUAL_EQUAL = 19,
							TokenNameLESS_EQUAL = 13,
							TokenNameGREATER_EQUAL = 14,
							TokenNameNOT_EQUAL = 20,
							TokenNameLEFT_SHIFT = 18,
							TokenNameRIGHT_SHIFT = 12,
							TokenNameUNSIGNED_RIGHT_SHIFT = 15,
							TokenNamePLUS_EQUAL = 69,
							TokenNameMINUS_EQUAL = 70,
							TokenNameMULTIPLY_EQUAL = 71,
							TokenNameDIVIDE_EQUAL = 72,
							TokenNameAND_EQUAL = 73,
							TokenNameOR_EQUAL = 74,
							TokenNameXOR_EQUAL = 75,
							TokenNameREMAINDER_EQUAL = 76,
							TokenNameLEFT_SHIFT_EQUAL = 77,
							TokenNameRIGHT_SHIFT_EQUAL = 78,
							TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 79,
							TokenNameOR_OR = 26,
							TokenNameAND_AND = 25,
							TokenNamePLUS = 1,
							TokenNameMINUS = 2,
							TokenNameNOT = 65,
							TokenNameREMAINDER = 5,
							TokenNameXOR = 22,
							TokenNameAND = 21,
							TokenNameMULTIPLY = 4,
							TokenNameOR = 23,
							TokenNameTWIDDLE = 66,
							TokenNameDIVIDE = 6,
							TokenNameGREATER = 17,
							TokenNameLESS = 7,
							TokenNameLPAREN = 28,
							TokenNameRPAREN = 30,
							TokenNameLBRACE = 41,
							TokenNameRBRACE = 33,
							TokenNameLBRACKET = 9,
							TokenNameRBRACKET = 84,
							TokenNameSEMICOLON = 29,
							TokenNameQUESTION = 24,
							TokenNameCOLON = 64,
							TokenNameCOMMA = 32,
							TokenNameDOT = 3,
							TokenNameEQUAL = 68,
							TokenNameAT = 37,
							TokenNameELLIPSIS = 121,
							TokenNameARROW = 114,
							TokenNameCOLON_COLON = 8,
							TokenNameBeginLambda = 87,
							TokenNameBeginIntersectionCast = 67,
							TokenNameBeginTypeArguments = 99,
							TokenNameAT308 = 31,
							TokenNameAT308DOTDOTDOT = 130,
							TokenNameBeginCaseExpr = 81,
							TokenNameRestrictedIdentifierYield = 90,
							TokenNameRestrictedIdentifierrecord = 85,
							TokenNameRestrictedIdentifiersealed = 43,
							TokenNameRestrictedIdentifierpermits = 128,
							TokenNameBeginCaseElement = 131,
							TokenNameRestrictedIdentifierWhen = 132,
							TokenNameBeginRecordPattern = 133,
							TokenNameEOF = 63,
							TokenNameERROR = 139;
}
