/*******************************************************************************
 * Copyright (c) 2000, 2009 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameWHITESPACE = 1000,
		TokenNameCOMMENT_LINE = 1001,
		TokenNameCOMMENT_BLOCK = 1002,
		TokenNameCOMMENT_JAVADOC = 1003;

	int TokenNameIdentifier = 23,
		TokenNameabstract = 33,
		TokenNameassert = 74,
		TokenNameboolean = 44,
		TokenNamebreak = 75,
		TokenNamebyte = 45,
		TokenNamecase = 102,
		TokenNamecatch = 103,
		TokenNamechar = 46,
		TokenNameclass = 71,
		TokenNamecontinue = 76,
		TokenNameconst = 108,
		TokenNamedefault = 86,
		TokenNamedo = 77,
		TokenNamedouble = 47,
		TokenNameelse = 104,
		TokenNameenum = 100,
		TokenNameextends = 87,
		TokenNamefalse = 57,
		TokenNamefinal = 34,
		TokenNamefinally = 105,
		TokenNamefloat = 48,
		TokenNamefor = 78,
		TokenNamegoto = 109,
		TokenNameif = 79,
		TokenNameimplements = 107,
		TokenNameimport = 101,
		TokenNameinstanceof = 11,
		TokenNameint = 49,
		TokenNameinterface = 84,
		TokenNamelong = 50,
		TokenNamenative = 35,
		TokenNamenew = 55,
		TokenNamenull = 58,
		TokenNamepackage = 85,
		TokenNameprivate = 36,
		TokenNameprotected = 37,
		TokenNamepublic = 38,
		TokenNamereturn = 80,
		TokenNameshort = 51,
		TokenNamestatic = 32,
		TokenNamestrictfp = 39,
		TokenNamesuper = 53,
		TokenNameswitch = 81,
		TokenNamesynchronized = 40,
		TokenNamethis = 54,
		TokenNamethrow = 82,
		TokenNamethrows = 106,
		TokenNametransient = 41,
		TokenNametrue = 59,
		TokenNametry = 83,
		TokenNamevoid = 52,
		TokenNamevolatile = 42,
		TokenNamewhile = 72,
		TokenNameIntegerLiteral = 60,
		TokenNameLongLiteral = 61,
		TokenNameFloatingPointLiteral = 62,
		TokenNameDoubleLiteral = 63,
		TokenNameCharacterLiteral = 64,
		TokenNameStringLiteral = 65,
		TokenNamePLUS_PLUS = 9,
		TokenNameMINUS_MINUS = 10,
		TokenNameEQUAL_EQUAL = 17,
		TokenNameLESS_EQUAL = 12,
		TokenNameGREATER_EQUAL = 13,
		TokenNameNOT_EQUAL = 18,
		TokenNameLEFT_SHIFT = 19,
		TokenNameRIGHT_SHIFT = 14,
		TokenNameUNSIGNED_RIGHT_SHIFT = 15,
		TokenNamePLUS_EQUAL = 88,
		TokenNameMINUS_EQUAL = 89,
		TokenNameMULTIPLY_EQUAL = 90,
		TokenNameDIVIDE_EQUAL = 91,
		TokenNameAND_EQUAL = 92,
		TokenNameOR_EQUAL = 93,
		TokenNameXOR_EQUAL = 94,
		TokenNameREMAINDER_EQUAL = 95,
		TokenNameLEFT_SHIFT_EQUAL = 96,
		TokenNameRIGHT_SHIFT_EQUAL = 97,
		TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 98,
		TokenNameOR_OR = 27,
		TokenNameAND_AND = 26,
		TokenNamePLUS = 1,
		TokenNameMINUS = 2,
		TokenNameNOT = 67,
		TokenNameREMAINDER = 5,
		TokenNameXOR = 22,
		TokenNameAND = 20,
		TokenNameMULTIPLY = 4,
		TokenNameOR = 24,
		TokenNameTWIDDLE = 68,
		TokenNameDIVIDE = 6,
		TokenNameGREATER = 16,
		TokenNameLESS = 7,
		TokenNameLPAREN = 30,
		TokenNameRPAREN = 29,
		TokenNameLBRACE = 69,
		TokenNameRBRACE = 43,
		TokenNameLBRACKET = 8,
		TokenNameRBRACKET = 70,
		TokenNameSEMICOLON = 28,
		TokenNameQUESTION = 25,
		TokenNameCOLON = 66,
		TokenNameCOMMA = 31,
		TokenNameDOT = 3,
		TokenNameEQUAL = 73,
		TokenNameAT = 21,
		TokenNameELLIPSIS = 99,
		TokenNameEOF = 56,
		TokenNameERROR = 110;
}
