on: pull_request

name: Check for merge commits

permissions:
  pull-requests: read

jobs:
  message-check:
    name: Block Merge Commits

    runs-on: ubuntu-latest

    steps:
      - name: Block Merge Commits
        uses: Morishiri/block-merge-commits-action@a4554c78def8d874966a8d1e20e2971121443755
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
